/**
 * Closed vocabularies for catalog fields editable via combo box.
 * Keep in sync with the equivalent lists in
 * `apps/backend/src/db/models.py` (e.g. `GEOGRAPHIC_FOCUS_OPTIONS`).
 */
export const GEOGRAPHIC_FOCUS_OPTIONS = [
  "EEUU",
  "Desarrollados ex-US",
  "Emergentes ex-Perú",
  "Latam ex-Perú",
  "Perú",
] as const;

export const CURRENCY_OPTIONS = ["Dólares", "Soles"] as const;

/**
 * Reference list only — "Administrador" accepts any free-text value.
 * These are just pre-existing names offered as shortcuts in the dropdown;
 * unlike the other catalog fields, this is not enforced on the backend.
 */
export const ADMINISTRATOR_OPTIONS = [
  "ACRES Sociedad Titulizadora S.A",
  "AFP Habitat",
  "Amara Foods EIRL",
  "American Ventures",
  "Art Atlas S.R.L",
  "Aurora Grupo Inmobiliario",
  "Banco comercio",
  "Baring",
  "Barings",
  "BBVA SAB",
  "BBVA SAF",
  "BCP",
  "Blum SAF",
  "BNP Paribas",
  "BNY",
  "BTG Pactual SAB",
  "BTG Pactual SAF",
  "Caja Arequipa",
  "Caja Huancayo",
  "Caja Piura",
  "Cash o efectivo",
  "Celta Contratistas",
  "Charles Schwab",
  "Citibank",
  "Compartamos",
  "Compass SAF",
  "Cooperativa Kori",
  "Core Capital",
  "Coril",
  "Coril SAF",
  "Credicorp Capital SAB",
  "Credicorp Capital SAF",
  "El Dorado SAF",
  "Faro Capital / Edifica",
  "Fidelity",
  "Financiera Oh",
  "Financiera surgir",
  "Flip",
  "GSDynamic",
  "HAPI",
  "HSBC",
  "Inteligo Bank",
  "Inteligo SAB",
  "Interactive Brokers",
  "Interbank",
  "Interfondos SAF",
  "Inversiones directas en empresas fuera de Peru",
  "Inversiones directas en empresas Peru",
  "Inversiones directas en propiedades fuera de peru",
  "Inversiones directas en propiedades Peru",
  "JPM",
  "Kallpa SAB",
  "LarrainVial SAB",
  "LPL",
  "Macrocapitales SAF",
  "Mapfre",
  "Medalist Partners",
  "Northern Trust",
  "Numa",
  "Pacifico Seguros",
  "PAHO",
  "Pershing",
  "Pichincha",
  "Prisma Inmobiliaria",
  "Produbanco",
  "Propio",
  "Propio / Exchange",
  "Prudential SAF",
  "S &T Comunicaciones Integral",
  "Sabadell",
  "Scotia Fondos SAF",
  "Scotia SAB",
  "Seminario SAB",
  "State Street",
  "Sura",
  "Sura SAB",
  "Sura SAF",
  "Tyba - Credicorp",
  "UBS",
  "Vanguard",
  "Zest Capital",
] as const;

export const ASSET_CLASS_OPTIONS = [
  "Inmobiliario Directo",
  "Mercados Publicos - Fijo",
  "Mercados Publicos - Variable",
  "Mercados Privados",
  "Club deals",
  "Cash y Otros",
] as const;

export const UNDERLYING_OPTIONS = [
  "Acciones Peru",
  "Bonos Corporativos Investment Grade (AAA–BBB)",
  "Bonos High Yield",
  "Bonos Latinoamérica",
  "Bonos Mercados Emergentes (Global)",
  "Bonos Perú",
  "Cash",
  "Club Deals Deuda Privada Peru",
  "Club Deals Deuda Privada Usa y otros",
  "Club Deals Otros Peru",
  "Club Deals Otros USA",
  "Club Deals Real Estate Peru",
  "Club Deals Real Estate USA y Otros",
  "Commodities",
  "Cripto",
  "Desarrollados ex US",
  "Hedge Funds",
  "Infrastructure Privada",
  "Mercados Emergentes ex Perú",
  "Oro",
  "Private Credit  Subordinated",
  "Private Credit Senior",
  "Private Equity",
  "Propiedades Directas Exterior",
  "Propiedades Directas Perú",
  "Real Estate Privado (Fondos)",
  "REITs Públicos",
  "US Large Cap",
  "US Mid & Small Cap",
  "US Treasuries – Largo Plazo",
  "US Treasuries Corto Plazo",
  "Venture Capital",
] as const;
