services:
  web:
    image: ${ECR_REGISTRY}/${ECR_REPO_FRONTEND}:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${MEMORY_WEB}
    restart: always
    env_file: .env
    environment:
      - NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID=agent
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`boba-fett.sabbi.com`)
      - traefik.http.routers.web.entrypoints=websecured
      - traefik.http.routers.web.tls.certresolver=letsencrypt
      - traefik.http.services.web.loadbalancer.server.port=3000
    depends_on:
      - backend

  backend:
    image: ${ECR_REGISTRY}/${ECR_REPO_BACKEND}:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${MEMORY_BACKEND}
    restart: always
    env_file: .env
    environment:
      - LANGSMITH_TRACING=true
      - LANGSMITH_PROJECT=boba-fett-v3
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`boba-fett-api.sabbi.com`)
      - traefik.http.routers.backend.entrypoints=websecured
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8000

volumes:
  letsencrypt:
