"""encrypt sensitive columns

Revision ID: 4c0a04508674
Revises: fc163426f0af
Create Date: 2026-07-23 14:01:03.026729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c0a04508674'
down_revision = 'fc163426f0af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # -- Encryption: NUMERIC → TEXT for encrypted amount storage --
    op.execute("ALTER TABLE products DROP CONSTRAINT IF EXISTS products_amount_check")
    op.alter_column('products', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=False,
               postgresql_using='amount::text')
    op.alter_column('portfolio_snapshots', 'total_amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               postgresql_using='total_amount::text')

    # -- Encryption: JSONB → TEXT for encrypted blob storage --
    op.alter_column('snapshot_products', 'product_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=False,
               postgresql_using='product_data::text')
    op.alter_column('portfolio_changes', 'before_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True,
               postgresql_using='before_state::text')
    op.alter_column('portfolio_changes', 'after_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True,
               postgresql_using='after_state::text')

    # -- geographic_focus: TEXT → JSONB with data backfill --
    # Backfill plain text values to JSON arrays before type conversion
    op.execute("""
        UPDATE products
        SET geographic_focus = CASE
            WHEN geographic_focus IS NOT NULL AND geographic_focus != ''
            THEN jsonb_build_array(jsonb_build_object('name', geographic_focus, 'percentage', 100))::text
            ELSE '[]'
        END
    """)
    op.execute("ALTER TABLE products ALTER COLUMN geographic_focus DROP DEFAULT")
    op.alter_column('products', 'geographic_focus',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="geographic_focus::jsonb")
    op.execute("ALTER TABLE products ALTER COLUMN geographic_focus SET DEFAULT '[]'::jsonb")

    op.execute("""
        UPDATE product_catalog
        SET geographic_focus = CASE
            WHEN geographic_focus IS NOT NULL AND geographic_focus != ''
            THEN jsonb_build_array(jsonb_build_object('name', geographic_focus, 'percentage', 100))::text
            ELSE '[]'
        END
    """)
    op.execute("ALTER TABLE product_catalog ALTER COLUMN geographic_focus DROP DEFAULT")
    op.alter_column('product_catalog', 'geographic_focus',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="geographic_focus::jsonb")
    op.execute("ALTER TABLE product_catalog ALTER COLUMN geographic_focus SET DEFAULT '[]'::jsonb")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snapshot_products', 'product_data',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('products', 'geographic_focus',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('products', 'amount',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('product_catalog', 'geographic_focus',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('portfolio_snapshots', 'total_amount',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('portfolio_changes', 'after_state',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('portfolio_changes', 'before_state',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
